# Generated by Django 2.1.5 on 2019-03-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190304_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='скидка')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Окончание')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned', models.BooleanField(verbose_name='Возврат')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Sale', verbose_name='Скидка')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Seat', verbose_name='Место')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Show', verbose_name='Сеанс')),
            ],
        ),
    ]
